version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-restaurant-franchise
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: M@@LSIC€SI2024
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
