name: Infrastructure Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy infrastructure with Terraform
      shell: bash
      working-directory: terraform
      run: |
        terraform init
        terraform apply -var-file='./goodfood.tfvars' -auto-approve
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_DEFAULT_USER }}
        TF_VAR_RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_DEFAULT_PASS }}
