name: Test Azure Identité Managée

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Create Storage account
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage account create --name stcarocjfprd02 --resource-group rg-github-actions --location francecentral --sku Standard_LRS